apiVersion: apps/v1
kind: Deployment
metadata:
  name: weenie-deployment
  labels:
    app: weenie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weenie-app
  template:
    metadata:
      labels:
        app: weenie-app
    spec:
      containers:
      - name: weenie-container
        image: thecontainerregistry.azurecr.io/weenie-image:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weenie-service
spec:
  selector:
    app: weenie-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
